'use strict';

const MODULE_VERSION = 'AI_DETECTION_PROVENANCE_V1';

const EXPLICIT_DISCLOSURE_PATTERNS = Object.freeze([
  { label: 'C2PA or Content Credentials marker', regex: /\bc2pa\b|content credentials?/i },
  { label: 'Explicit AI-generated disclosure', regex: /\b(?:ai[- ]generated|generated by ai|synthetic media|synthetically generated)\b/i },
  { label: 'Adobe Firefly disclosure', regex: /\badobe firefly\b/i }
]);

const AI_TOOL_PATTERNS = Object.freeze([
  { label: 'DALL-E or OpenAI image marker', regex: /\bdall[- ]?e\b|\bopenai image\b/i },
  { label: 'Midjourney marker', regex: /\bmidjourney\b/i },
  { label: 'Stable Diffusion marker', regex: /\bstable diffusion\b|\bautomatic1111\b|\bcomfyui\b/i },
  { label: 'Runway marker', regex: /\brunway(?:ml)?\b/i },
  { label: 'Sora marker', regex: /\bopenai sora\b|\bsora video\b/i },
  { label: 'Pika marker', regex: /\bpika(?: labs)?\b/i },
  { label: 'Leonardo AI marker', regex: /\bleonardo\.?ai\b/i },
  { label: 'Ideogram marker', regex: /\bideogram\b/i },
  { label: 'FLUX model marker', regex: /\bflux(?:\.1)?\b[^\r\n]{0,30}\b(?:model|schnell|dev|pro)\b/i }
]);

function searchableText(buffer) {
  const latin = buffer.toString('latin1');
  const utf8 = buffer.toString('utf8');
  return (latin + '\n' + utf8).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]+/g, ' ');
}

function collectMatches(text, patterns) {
  const matches = [];
  patterns.forEach(function (entry) {
    if (entry.regex.test(text)) matches.push(entry.label);
  });
  return matches;
}

function inspect(preparedMedia) {
  if (!preparedMedia || !Buffer.isBuffer(preparedMedia.buffer)) {
    throw new Error('AI provenance inspection requires validated media bytes.');
  }
  const text = searchableText(preparedMedia.buffer);
  const explicit = collectMatches(text, EXPLICIT_DISCLOSURE_PATTERNS);
  const tools = collectMatches(text, AI_TOOL_PATTERNS);
  const signals = explicit.concat(tools).filter(function (value, index, list) {
    return list.indexOf(value) === index;
  }).slice(0, 10);

  let status = 'NO_AI_PROVENANCE_FOUND';
  let answer = 'No embedded AI provenance or generator marker was found.';
  let explanation = 'This does not prove the file is human-created. Metadata can be missing, removed, or changed, and visual or audio detection is not active yet.';

  if (explicit.length) {
    status = 'AI_DISCLOSURE_FOUND';
    answer = 'An embedded AI or synthetic-media disclosure was found.';
    explanation = 'The file contains provenance or disclosure text associated with AI-generated or synthetic media.';
  } else if (tools.length) {
    status = 'AI_TOOL_METADATA_FOUND';
    answer = 'An embedded AI-tool marker was found.';
    explanation = 'The file contains metadata text associated with an AI-generation tool. This is a strong provenance signal, but the complete creation history may still be unavailable.';
  }

  return Object.freeze({
    version: MODULE_VERSION,
    status: status,
    answer: answer,
    explanation: explanation,
    signals: Object.freeze(signals),
    visualOrAudioContentAnalyzed: false,
    metadataOnly: true
  });
}

module.exports = Object.freeze({
  MODULE_VERSION: MODULE_VERSION,
  inspect: inspect
});
